name: CI/CD con Maven, Análisis y Despliegue

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # También se activa cuando creas una etiqueta como v1.0

jobs:
  # TRABAJO 1: CONSTRUIR Y ANALIZAR
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Ejecutar pruebas y análisis con Maven
        run: mvn -B verify -f ProyectoCalidad/pom.xml

  # TRABAJO 2: DESPLEGAR
  deploy:
    # Condición 1: El trabajo anterior debe tener éxito
    needs: build-and-analyze
    # Condición 2: Solo se ejecuta si el evento fue crear una etiqueta
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Empaquetar la aplicación
        run: mvn -B package -f ProyectoCalidad/pom.xml

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: ProyectoCalidad/target/ProyectoCalidad-1.0-SNAPSHOT.jar