name: CI con Maven y Análisis de Calidad

# Se activa en cada push y pull request a la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    # El trabajo se ejecutará en una máquina virtual con Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el JDK 11 (la misma versión de tu pom.xml)
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Ejecuta el ciclo de vida de Maven hasta "verify"
      - name: Ejecutar pruebas y análisis con Maven
        # El comando ejecuta todo: compila, prueba, y corre Checkstyle, PMD y SpotBugs
        # Se usa "-f" para indicar la ruta a tu pom.xml dentro de la carpeta ProyectoCalidad
        run: mvn -B verify -f ProyectoCalidad/pom.xml
